### ISSUE TITLE
IBlockState#getPropertyNames

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#103] opened 2016-02-25 14:00 UTC
This method (`func_177227_a
`) is currently `getPropertyNames`, but it returns `Collection<IProperty>` not a collection of names.

`getProperties` is already used by another method

**Comment by The-Fireplace** [comment] 2016-02-25 15:07
How about naming it getPropertyCollection

**Comment by bspkrs** [comment] 2016-02-26 02:56
This is a duplicate of #44

**Closed** 2016-02-26 05:07 UTC
Labels: duplicate, mappings
