### ISSUE TITLE
WorldChunkManager -> BiomeGenerator

### ISSUE THREAD

**Issue by Zidane** [ModCoderPack/MCPBot-Issues#93] opened 2016-02-24 21:59 UTC

**Comment by simon816** [comment] 2016-02-24 22:01
https://github.com/ModCoderPack/MCPBot-Issues/issues/38

**Comment by gabizou** [comment] 2016-02-24 22:01
Duplicate of https://github.com/ModCoderPack/MCPBot-Issues/issues/38

**Comment by Zidane** [comment] 2016-02-24 22:01
Didn't even realize that was gotten to :D.

**Closed** 2016-02-24 22:01 UTC
