### ISSUE TITLE
Valid SRG names not recognized

### ISSUE THREAD

**Issue by micahcowan** [ModCoderPack/MCPBot-Issues#150] opened 2016-03-08 01:26 UTC
```
17:10 <micahcowan> gm func_189213_a
17:10 -MCPBot_Reborn(~MCPBot_Re@mcpbot.bspk.rs)- No results found.
```

Time zone is PST (GMT-0800).

`func_189213_a` is a legitimate method name in `joined.srg`, but the bot doesn't recognize it for querying or naming.

(This is the only instance I'm currently aware of, but I imagine if it can happen to one... it does seem to be pretty rare, though, and this might actually turn out to be the only instance.)

**Comment by kashike** [comment] 2016-03-08 01:27
Duplicate of https://github.com/ModCoderPack/MCPBot-Issues/issues/142

**Closed** 2016-03-08 02:27 UTC

**Comment by bspkrs** [comment] 2016-03-08 02:48
fyi this is now resolved
